# Generated by Django 5.1.4 on 2025-01-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('Specializations', models.ManyToManyField(to='sgcm.specialization')),
            ],
        ),
    ]
