# Generated by Django 5.1.4 on 2025-01-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgcm', '0002_specialization_healthprofessional'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='icon',
            field=models.ImageField(blank=True, upload_to='specialization/icons/'),
        ),
    ]
