# Generated by Django 5.1.4 on 2025-01-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgcm', '0003_specialization_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofessional',
            name='name',
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='address',
            field=models.CharField(default='Sem endereço', max_length=255),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='cep',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='crm',
            field=models.CharField(default='Sem CRM', max_length=20),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='medical_id',
            field=models.FileField(blank=True, null=True, upload_to='medical_ids/'),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='neighborhood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='rg',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
