# Generated by Django 5.1.4 on 2025-01-09 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgcm', '0004_remove_healthprofessional_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofessional',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthprofessional',
            name='crm',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
