# Generated by Django 5.1.4 on 2025-01-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgcm', '0005_healthprofessional_user_alter_healthprofessional_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofessional',
            name='full_name',
            field=models.CharField(default='Nome não especificado', max_length=255),
        ),
    ]
